[versions]
angus-mail = '2.0.5'
assertj-core = '3.27.6'
bouncycastle = '1.83'
jakarta-mail-api = '2.1.5'
jasper-reports = '7.0.3'
junit-jupiter = '6.0.1'
junit-platform-runner = '1.14.1'
logback = '1.5.21'
odftoolkit = '0.12.0'
openpdf = '2.4.0'
qrinvoice = '1.23'
slf4j = '2.0.17'

[libraries]
angus-mail = { module = 'org.eclipse.angus:jakarta.mail', version.ref = 'angus-mail' }
assertj-core = { module = 'org.assertj:assertj-core', version.ref = 'assertj-core' }
bouncycastle-bcprov = { module = 'org.bouncycastle:bcprov-jdk18on', version.ref = 'bouncycastle' }
jakarta-mail-api = { module = 'jakarta.mail:jakarta.mail-api', version.ref = 'jakarta-mail-api' }
jasper-reports = { module = 'net.sf.jasperreports:jasperreports', version.ref = 'jasper-reports' }
jasper-reports-functions = { module = 'net.sf.jasperreports:jasperreports-functions', version.ref = 'jasper-reports' }
jasper-reports-jdt = { module = 'net.sf.jasperreports:jasperreports-jdt', version.ref = 'jasper-reports' }
jasper-reports-metadata = { module = 'net.sf.jasperreports:jasperreports-metadata', version.ref = 'jasper-reports' }
jasper-reports-pdf = { module = 'net.sf.jasperreports:jasperreports-pdf', version.ref = 'jasper-reports' }
junit-jupiter-api = { module = 'org.junit.jupiter:junit-jupiter-api', version.ref = 'junit-jupiter' }
junit-jupiter-engine = { module = 'org.junit.jupiter:junit-jupiter-engine', version.ref = 'junit-jupiter' }
junit-platform-runner = { module = 'org.junit.platform:junit-platform-runner', version.ref = 'junit-platform-runner' }
logback-classic = { module = 'ch.qos.logback:logback-classic', version.ref = 'logback' }
logback-core = { module = 'ch.qos.logback:logback-core', version.ref = 'logback' }
odftoolkit = { module = 'org.odftoolkit:odfdom-java', version.ref = 'odftoolkit' }
openpdf = { module = 'com.github.librepdf:openpdf', version.ref = 'openpdf' }
qrinvoice-core = { module = 'ch.codeblock.qrinvoice.core:qrinvoice-core', version.ref = 'qrinvoice' }
qrinvoice-openpdf = { module = 'ch.codeblock.qrinvoice.openpdf:qrinvoice-openpdf', version.ref = 'qrinvoice' }
slf4j-api = { module = 'org.slf4j:slf4j-api', version.ref = 'slf4j' }

[plugins]
ben-manes-versions = { id = 'com.github.ben-manes.versions', version = '0.53.0' }
nemerosa-versioning = { id = 'net.nemerosa.versioning', version = '3.1.0' }
owasp-dependencycheck = { id = 'org.owasp.dependencycheck', version = '12.1.9' }
